node {
    def mavenHome = tool name: 'Maven 3.9.0', type: 'maven'

    stage('Build') {
        sh "${mavenHome}/bin/mvn -B -DskipTests clean package"
    }

    stage('Test') {
        sh "${mavenHome}/bin/mvn test"
        junit 'target/surefire-reports/*.xml'
    }

    stage('Deliver') {
        withEnv(["PATH+MAVEN=${mavenHome}/bin"]) {
            sh './jenkins/scripts/deliver.sh'
        }
    }
}
