node {
    def mavenHome = tool name: 'Maven 3.9.0', type: 'maven'

    stage('Build') {
        sh "${mavenHome}/bin/mvn -B -DskipTests clean package"
        sh 'ls -l target/'

    }

    stage('Test') {
        sh "${mavenHome}/bin/mvn test"
        junit 'target/surefire-reports/*.xml'
    }

    stage('Deliver') {
        withEnv(["PATH+MAVEN=${mavenHome}/bin"]) {
            sh './jenkins/scripts/deliver.sh'
        }
    }

    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan)'
    }

    stage('Deploy') {
        def ec2Ip = '18.218.217.151'
        def ec2User = 'admin'
        def appJar = "target/myapp.jar"

        withCredentials([file(credentialsId: 'my-ec2-key', variable: 'EC2_KEY')]) {
            sh '''
            chmod 600 $EC2_KEY
            scp -o StrictHostKeyChecking=no -i $EC2_KEY target/my-app-1.0-SNAPSHOT.jar admin@18.218.217.151:/home/admin/myapp.jar
            ssh -o StrictHostKeyChecking=no -i $EC2_KEY admin@18.218.217.151 "nohup java -jar /home/admin/myapp.jar > myapp.log 2>&1 &"
            '''
        }

        sleep 60;
    }
}
